Refactor Model Zoo
furiosa-ai/furiosa-models pull request #166
Opened 2023-08-07 07:26 UTC by furiosamg

1. 더 이상 모델 클래스를 만들 때 모든 바이너리를 다운로드 하지 않습니다.
a. 대신, 해당 필드에 접근할 때 lazy load 합니다.
b. 한 번에 모든 바이너리를 다운로드 받는 resolve_all 함수가 추가되었습니다.
2. 모델 클래스를 만들기 위해 `Model.load()`, `Model.load_async()` 같은 함수를 사용하지 않습니다.
a. 직관적으로 `Model()`을 불러 모델 클래스를 만들 수 있습니다.
b. 어떤 postprocess를 사용할지는 기존과 비슷하게 `Model(postprocessor_type="RUST")` 를 이용해 정할 수 있습니다.
c. 이제 파일을 로컬에 캐시하므로, Model load가 오래 걸리는 것은 컴퓨터당 한 번 정도일 것인데 이걸 최적화하겠다고 async initializer를 쓸 이유가 없다고 판단
d. 네트워크 환경이 좋지 않은 곳에서 실행하는 경우가 많은데, 이 때 어차피 network throughput에 block되므로 concurrent 하게 바이너리를 다운로드 받을 이유가 없음
3. Pydantic 2.x 버전으로 업그레이드했습니다.
a. 알맞은 postprocessor 를 사용해 init 했는지 validation하는 과정이 추가되었습니다.
4. Pydantic에 어울리도록 (Dataclass 다운) 각종 필드등을 함수나 클래스 등에서 순수한 값으로 변경하였습니다.
a. Python에 interface, abstract property 같은 기능이 없어 Class variable이 남아 있습니다..
5. `furiosa-models list` 나  `furiosa-models desc` 같은 명령이 빨라졌습니다.
a. Lazy loading 덕분에, 혹은 아예 클래스를 생성하지 않고 메타 클래스 상태에서 명령을 수행합니다.
6. 모델 필드 이름들의 변경이 있을 예정입니다. (의견 주세요)
	a. 원본 f32 onnx|tflite 필드 `source` -> `origin`
		- 이유: furiosa rt에서 model source라는 이름으로 Runner의 입력이 될 수 있는 것들을 총칭하기 때문에 헷갈릴 여지가 있다고 판단
	b. Calibration range 필드 `calib_yaml` -> `tensor_name_to_range`
		- 일단, yaml 대신 Python dict를 돌려주도록 변경
		- furiosa-quantizer 의 이름에 맞춤
	c. ENF 필드 `enf`, `enf_1pe` -> `model_source()` , `model_source(num_pe=1)`
		- ENF라는 이름을 사용자에게 노출할 이유가 없음
		- 함수로 바꿔서 pe 수를 조정 가능하게 함, 추후엔 remove_lower 등 더 다양한 옵션을 지원하게 하려고 함

2023-08-09 04:13 UTC, furiosa-infra commented
## Pip freeze result for ssd-mobilenet
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 04:13 UTC, furiosa-infra commented
## Pip freeze result for yolov5
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 04:13 UTC, furiosa-infra commented
## Pip freeze result for resnet50
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 04:39 UTC, furiosa-infra commented
## Pip freeze result for ssd-mobilenet
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 05:42 UTC, furiosa-infra commented
## Pip freeze result for ssd-mobilenet
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:06 UTC, furiosa-infra commented
## Pip freeze result for ssd-mobilenet
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:11 UTC, furiosa-infra commented
3853bff ci: preload libgomp in regression tests
```

----------------------------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------------------------
Name (time in ms)                                                Min                Max               Mean            StdDev             Median               IQR            Outliers       OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy     3.7822 (1.0)      31.6890 (1.0)       7.7506 (1.0)      0.9055 (1.0)       7.9104 (1.0)      0.6854 (1.0)       820;483  129.0223 (1.0)        5000           1
test_mlcommons_ssd_mobilenet_accuracy                         5.1636 (1.37)     38.4813 (1.21)     11.5577 (1.49)     1.4195 (1.57)     11.5132 (1.46)     1.3940 (2.03)     1122;283   86.5227 (0.67)       5000           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 06:36 UTC, furiosa-infra commented
## Pip freeze result for ssd-resnet34
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:37 UTC, furiosa-infra commented
## Pip freeze result for efficientnet-v2-s
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:38 UTC, furiosa-infra commented
## Pip freeze result for resnet50
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:40 UTC, furiosa-infra commented
## Pip freeze result for yolov5
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:41 UTC, furiosa-infra commented
## Pip freeze result for efficientnet-b0
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:49 UTC, furiosa-infra commented
de224ad fix: use f32 preprocess for onnx example
```

---------------------------------------------------- benchmark: 1 tests ----------------------------------------------------
Name (time in ms)                    Min       Max     Mean  StdDev   Median     IQR   Outliers      OPS  Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------
test_efficientnetv2s_accuracy     4.6340  268.7292  13.9764  6.6025  13.3414  3.1459  1667;1861  71.5492   50000           1
----------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 06:49 UTC, furiosa-infra commented
de224ad fix: use f32 preprocess for onnx example
```

----------------------------------------------------- benchmark: 1 tests -----------------------------------------------------
Name (time in ms)                       Min       Max    Mean  StdDev  Median     IQR   Outliers       OPS  Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy     1.1763  129.8883  4.4347  1.8086  4.1032  1.1755  4647;3393  225.4926   50000           1
------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 06:50 UTC, furiosa-infra commented
## Pip freeze result for yolov5
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.24.1
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
markdown-it-py==3.0.0
matplotlib==3.7.2
mdurl==0.1.2
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==1.13.1
torchvision==0.14.1
tqdm==4.65.2
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 06:51 UTC, furiosa-infra commented
de224ad fix: use f32 preprocess for onnx example
```

---------------------------------------------------- benchmark: 1 tests ---------------------------------------------------
Name (time in ms)                   Min       Max     Mean  StdDev   Median     IQR   Outliers      OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------
test_efficientnetb0_accuracy     3.7350  316.6901  11.5822  6.6971  11.1857  2.7542  1105;1613  86.3397   50000           1
---------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 06:55 UTC, furiosa-infra commented
de224ad fix: use f32 preprocess for onnx example
```

------------------------------------------------------------------------------------------------------- benchmark: 2 tests ------------------------------------------------------------------------------------------------------
Name (time in ms)                                                Min                 Max                Mean             StdDev              Median                IQR            Outliers      OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy     36.5905 (1.0)      466.9487 (1.0)       51.3675 (1.0)      12.1519 (1.0)       50.6249 (1.0)       3.3404 (1.0)        93;277  19.4676 (1.0)        5000           1
test_mlcommons_ssd_resnet34_accuracy                         86.0933 (2.35)     973.7019 (2.09)     116.7616 (2.27)     23.1291 (1.90)     114.1347 (2.25)     17.6526 (5.28)      424;150   8.5645 (0.44)       5000           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 07:48 UTC, furiosa-infra commented
fdce245 fix: use torch's libgomp explicitly
```

----------------------------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------------------------
Name (time in ms)                                                Min                Max               Mean            StdDev             Median               IQR            Outliers       OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy     4.4453 (1.0)      22.0371 (1.0)       8.4612 (1.0)      1.4678 (1.31)      8.5355 (1.0)      1.3186 (1.37)     1351;505  118.1862 (1.0)        5000           1
test_mlcommons_ssd_mobilenet_accuracy                         5.4690 (1.23)     23.4960 (1.07)     11.2415 (1.33)     1.1219 (1.0)      11.3079 (1.32)     0.9599 (1.0)      1048;502   88.9562 (0.75)       5000           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 07:49 UTC, furiosa-infra commented
## Pip freeze result for yolov5
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 07:50 UTC, furiosa-infra commented
## Pip freeze result for efficientnet-b0
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 07:50 UTC, furiosa-infra commented
## Pip freeze result for efficientnet-v2-s
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:15 UTC, furiosa-infra commented
## Pip freeze result for efficientnet-v2-s
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:15 UTC, furiosa-infra commented
## Pip freeze result for ssd-mobilenet
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:16 UTC, furiosa-infra commented
## Pip freeze result for ssd-resnet34
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:18 UTC, furiosa-infra commented
## Pip freeze result for efficientnet-b0
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:19 UTC, furiosa-infra commented
236ac91 ci: find libgomp at very best effort
```

----------------------------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------------------------
Name (time in ms)                                                Min                Max               Mean            StdDev             Median               IQR            Outliers       OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy     4.0137 (1.0)      17.5513 (1.0)       7.7959 (1.0)      0.8721 (1.0)       7.9356 (1.0)      0.6441 (1.0)       848;570  128.2729 (1.0)        5000           1
test_mlcommons_ssd_mobilenet_accuracy                         5.3585 (1.34)     21.2240 (1.21)     10.8560 (1.39)     1.1726 (1.34)     10.8904 (1.37)     0.9979 (1.55)     1092;544   92.1149 (0.72)       5000           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 10:21 UTC, furiosa-infra commented
## Pip freeze result for resnet50
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:27 UTC, furiosa-infra commented
236ac91 ci: find libgomp at very best effort
```

--------------------------------------------------- benchmark: 1 tests ---------------------------------------------------
Name (time in ms)                   Min       Max     Mean  StdDev   Median     IQR  Outliers      OPS  Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------
test_efficientnetb0_accuracy     3.6514  473.7674  10.8450  7.7924  10.0403  2.9110  893;1374  92.2087   50000           1
--------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 10:27 UTC, furiosa-infra commented
236ac91 ci: find libgomp at very best effort
```

----------------------------------------------------- benchmark: 1 tests ----------------------------------------------------
Name (time in ms)                    Min         Max     Mean  StdDev   Median     IQR  Outliers      OPS  Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------
test_efficientnetv2s_accuracy     6.1493  1,048.7924  14.1586  8.5557  13.4201  3.1818  906;1509  70.6284   50000           1
-----------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 10:28 UTC, furiosa-infra commented
## Pip freeze result for yolov5
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.1.0
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.13.3
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.74
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.2
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-09 10:32 UTC, furiosa-infra commented
236ac91 ci: find libgomp at very best effort
```

----------------------------------------------------- benchmark: 1 tests -----------------------------------------------------
Name (time in ms)                       Min       Max    Mean  StdDev  Median     IQR   Outliers       OPS  Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy     1.2859  149.7867  4.6367  1.9440  4.1306  1.6258  4849;1608  215.6713   50000           1
------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 10:36 UTC, furiosa-infra commented
236ac91 ci: find libgomp at very best effort
```

-------------------------------------------------------------------------------------------------------- benchmark: 2 tests -------------------------------------------------------------------------------------------------------
Name (time in ms)                                                Min                   Max                Mean             StdDev              Median                IQR            Outliers      OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy     35.4283 (1.0)        498.8884 (1.0)       51.3501 (1.0)      10.3566 (1.0)       50.8919 (1.0)       3.2708 (1.0)        52;168  19.4742 (1.0)        5000           1
test_mlcommons_ssd_resnet34_accuracy                         92.5231 (2.61)     1,169.3603 (2.34)     128.7409 (2.51)     27.1627 (2.62)     126.3400 (2.48)     19.9443 (6.10)      299;100   7.7675 (0.40)       5000           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-09 16:38 UTC, furiosa-infra commented
834f7cf fix: use model_source over enf
```

------------------------------------------------------------------------------------------- benchmark: 2 tests -------------------------------------------------------------------------------------------
Name (time in ms)                            Min                 Max               Mean             StdDev             Median               IQR            Outliers      OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_yolov5m_accuracy (0001_834f7cf)      8.5326 (1.0)      305.6645 (1.0)      14.7899 (1.0)       9.7157 (1.0)      12.8629 (1.0)      4.5498 (1.0)       251;383  67.6138 (1.0)       10000           1
test_yolov5l_accuracy (0002_834f7cf)     11.7892 (1.38)     638.2718 (2.09)     18.1216 (1.23)     10.9321 (1.13)     15.6429 (1.22)     4.9771 (1.09)      455;643  55.1828 (0.82)      10000           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-10 03:03 UTC, furiosamg commented
커밋 정리하기 전 모든 regression test 성공하는 것까지 확인했습니다.

2023-08-10 03:04 UTC, furiosa-infra commented
## Pip freeze result for all
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.2.1
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.14.0
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.76
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.1.0
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.0
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-10 04:34 UTC, furiosa-infra commented
2841633 fix: use not-quantized preproc for onnx example
```

---------------------------------------------------------------------------------------------------------- benchmark: 9 tests ----------------------------------------------------------------------------------------------------------
Name (time in ms)                                                  Min                   Max                Mean              StdDev              Median                 IQR            Outliers       OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy                                1.4611 (1.0)        118.4826 (2.46)       7.5888 (1.0)        5.8192 (1.53)       5.4842 (1.0)        2.3894 (2.04)    5688;6994  131.7723 (1.0)       50000           1
test_efficientnetb0_accuracy                                    5.2490 (3.59)       267.5371 (5.56)      12.5537 (1.65)       6.9393 (1.82)      11.9294 (2.18)       2.0171 (1.72)     978;2868   79.6577 (0.60)      50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy       5.4944 (3.76)        48.1236 (1.0)       12.4112 (1.64)       5.9827 (1.57)       9.3145 (1.70)       5.6260 (4.80)      806;405   80.5723 (0.61)       5000           1
test_efficientnetv2s_accuracy                                   6.8149 (4.66)       350.6366 (7.29)      14.8518 (1.96)       6.8063 (1.79)      14.2350 (2.60)       2.4288 (2.07)     930;1650   67.3319 (0.51)      50000           1
test_mlcommons_ssd_mobilenet_accuracy                           6.9562 (4.76)       245.3414 (5.10)      11.0513 (1.46)       3.8031 (1.0)       10.4563 (1.91)       1.1732 (1.0)       439;692   90.4871 (0.69)       5000           1
test_yolov5m_accuracy                                           9.2291 (6.32)       281.0977 (5.84)      16.8433 (2.22)      10.8847 (2.86)      13.3270 (2.43)       6.1911 (5.28)     971;1051   59.3709 (0.45)      10000           1
test_yolov5l_accuracy                                          11.8674 (8.12)       631.1337 (13.11)     16.7725 (2.21)      10.6729 (2.81)      15.4910 (2.82)       3.2220 (2.75)       85;363   59.6215 (0.45)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy       39.4801 (27.02)      786.9761 (16.35)     52.3567 (6.90)      19.1570 (5.04)      51.2758 (9.35)       3.4326 (2.93)        7;225   19.0997 (0.14)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          102.8899 (70.42)    2,109.6694 (43.84)    289.7753 (38.18)    107.7437 (28.33)    288.0926 (52.53)    105.1287 (89.61)     692;219    3.4509 (0.03)       5000           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-10 09:34 UTC, senokay requested changes

2023-08-10 09:34 UTC, senokay commented on docs/examples/ssd_mobilenet_onnx.py
> +    inputs, contexts = mobilenet.preprocess(image, with_quantize=True)
제가 이해하기로는 `with_quantize` 관련해서 정확히 다음 두 가지 경우만 올바릅니다.

1. `quantize`를 실행하고 `preprocess`에 `with_quantize=True`를 넣을 경우
2. `quantize`를 실행하지 않고 `preprocess`에 `with_quantize=False`(기본값)를 넣을 경우

즉 의도는 모델이나 전처리 중 한 쪽이 양자화를 해야 한다는 것인데요, `with_quantize`라는 이름은 입력이 양자화되었다고 가정한다는 뜻인지 안에서 양자화를 더 하겠다는 뜻인지 알 수 없습니다. 전자를 의도하면 `assume_quantized`, 후자를 의도하면 `skip_quantize` 같은 이름으로 바꿔야 할 것 같습니다. 어느 쪽이 더 흔한지를 보고 기본값이 False가 되는 쪽을 선택하면 되지 않을까 싶어요.

2023-08-10 09:34 UTC, senokay commented on furiosa/models/vision/ssd_mobilenet/__init__.py
>                      raise FileNotFoundError(image)
변경 사항에 들어 있는 부분은 아니지만 이 뒷쪽에서 `with_quantize=False`일 때 `image`는 입력 이미지의 type을 그대로 물려 받습니다. 이를테면 입력을 `cv2.imread(path, cv2.IMREAD_ANYDEPTH)` 같은 걸로 읽었을 경우 그러할 수 있습니다(기본값은 항상 8비트로 변환하는 것으로 확인하긴 했습니다). 입력이 8비트로 고정되어 있으니만큼 해당 케이스에서는 최소한 assert는 넣을 필요가 있어 보입니다.

2023-08-10 09:34 UTC, senokay commented on furiosa/models/vision/ssd_resnet34/__init__.py
> -            family="ResNet",
실수로 누락되었습니다.

2023-08-10 09:34 UTC, senokay commented on furiosa/models/types.py
> +    postprocessor_type: Platform
아래의 property까지 합하면 세 종류의 값이 혼재되어 있습니다.

1. `postprocessor`: 말 그대로 이 모델에서 후처리에 사용할 callable
2. `postprocessor_map`: 각 platform 별로 사용되는 `postprocessor`의 mapping
3. `postprocessor_type`: 현재 사용되는 `postprocessor`가 어떤 platform인지

2는 CLI에서 사용한다고 인지하고 있습니다만 3은 `Model`에 들어 있어야 하는 게 아니라 `PostProcessor`의 class property여야 하지 맞지 않을까요. 이런 구조가 된 가장 큰 이유는 생성자에서 `platform`을 받으면 곧바로 `Model.__init__`에 보내서 `postprocessor_map`을 초기화함과 동시에 indexing에도 쓰려는 것일텐데요, 이게 목표라면 `__init__`을 오버로딩하는 게 더 나을 것 같습니다.

```python
class Model(ABC, BaseModel):
    postprocessor: PostProcessor = Field(..., repr=False, exclude=True)
    postprocessor_map: Mapping[Platform, Type[PostProcessor]] = Field(..., repr=False, exclude=True)
    # 이하 등등

    def __init__(
        self,
        postprocessor_map: Mapping[Platform, Type[PostProcessor]],
        postprocessor_type: Platform,
        **kwargs
    ):
        postprocessor = postprocessor_map[postprocessor_type]
        super().__init__(
            postprocessor=postprocessor, postprocessor_map=postprocessor_map, **kwargs
        )
```

이러면 `postprocessor_type`은 Model로 노출되지 않습니다.

2023-08-10 12:39 UTC, furiosamg commented
리뷰 주시기 전 변경 내용인 https://github.com/furiosa-ai/furiosa-models/pull/166/files/284163366d751009b4dfafab59a57f480326c102..055168b5d3900b40160989545cee4d54ace9a903
도 포함해버렸는데요.. (이 변경이 포함된 브랜치에서 작업하다가 그냥 올려버렸네요)
이 두 커밋의 변경은 추적하고 있지 않던 resnet34 예제를 돌리는 것과 Session 대신 Runner API 를 사용하는 변경입니다. 참고해주시면 감사하겠습니다

2023-08-10 12:44 UTC, furiosamg commented on furiosa/models/vision/resnet50/__init__.py
> +        if isinstance(image, str):
제안 주신 내용이 수도코드인거죠? https://github.com/furiosa-ai/furiosa-models/pull/166/commits/9ef66444d87783519cd43b64b608513fce839a0e#diff-f4bd919cc81403b49b53f1f6019362ab76d39fb9a15931a5da2d609637e05040R41-R49 에서 변경 후에 반영했습니다.
```python
def read_image_opencv_if_needed(image: Union[str, os.PathLike, ndarray]):
    if isinstance(image, ndarray):  # early return
        return image
    if isinstance(image, os.PathLike):  # resolve대신 os.PathLike는 __fspath__ 함수를 인터페이스로 제공하네요 돌려주는값은 bytes | str 인데 str이 기본입니다.
        image = image.__fspath__()  # imread only accepts str (opencv/opencv#15731)
    image = cv2.imread(image)
    if image is None:
        raise FileNotFoundError(image)
    return image
```

아 FileNotFound 에 에러가 있다는 걸 지금 이해했네요.. 바로 고쳐서 커밋하겠습니다.

2023-08-10 12:44 UTC, furiosamg commented on furiosa/models/types.py
> +        tasy_type: the task type of this model
d08e8ac34d3 에서 반영했습니다

2023-08-10 12:45 UTC, furiosamg commented on furiosa/models/client/api.py
> +    use_native = model.postprocessor_type != Platform.PYTHON
1339aaceb92cc 에서 PostProcessor 관련 큰 변경들과 함께 진행했습니다.

2023-08-10 12:46 UTC, furiosamg commented on furiosa/models/_utils.py
> +        import onnx
d08e8ac34d3efb 에서 import onnx도 try 안으로 옮겼고 에러 이름도 ExtraPackageRequired 로 바꿨습니다

2023-08-10 12:46 UTC, furiosamg commented on furiosa/models/_utils.py
> +    return base
d08e8ac34d3 에서 삭제했습니다

2023-08-10 12:47 UTC, furiosamg commented on docs/examples/ssd_mobilenet_onnx.py
> +    inputs, contexts = mobilenet.preprocess(image, with_quantize=True)
skip_quantize가 좀 더 직관적인것같아서 그렇게 바꿨습니다. skip_quantize의 기본값을 True로 주게 했는데 괜찮으신가요?

2023-08-10 13:35 UTC, furiosamg commented on pyproject.toml
> +    "numpy",
https://github.com/furiosa-ai/furiosa-models/pull/166/files#diff-0e0b1dc0663c5b9d12d29c4a978138dd9103815fe48eb5186e147e06c14f0e49
에서 추가하고
https://github.com/furiosa-ai/furiosa-models/commit/8ed435a6a3daf89a45a4976e3045acc8535966f0#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR36
에서 install 시 적용했습니다.

2023-08-10 13:45 UTC, furiosamg commented on furiosa/models/vision/ssd_resnet34/__init__.py
> -            family="ResNet",
https://github.com/furiosa-ai/furiosa-models/pull/166/commits/8ed435a6a3daf89a45a4976e3045acc8535966f0#diff-bbf9974f7c193d21a1a82292805d3c26a33481420f2f30a982bac947c2077c93R437
에서 복구했습니다 :) 감사합니다

2023-08-10 13:58 UTC, furiosamg commented on furiosa/models/types.py
> +    postprocessor_type: Platform
1339aaceb92cc 에서 전체적으로 변경했는데요, instantiate된 모델에서 postprocessor의 type이나 map을 갖고 있는게 어색하다는 성훈님 의견에 동의해서 제거하도록 바꿨습니다.

### `postprocessor_map`

postprocessor map은 각 모델의 `furiosa.models.type.Model` 의 field 대신 상속받은 각 모델의 class variable 로 가지고 있도록 했습니다.

> [참고](https://docs.pydantic.dev/latest/usage/models/#class-vars):
> ```python
> class SomeModel(Model, BaseModel):
>     postprocessor_map: Dict[Platform, Type[PostProcessor]] = dict(...)  # 불가.. 초기화가 불가능한 필드 취급
>     postprocessor_map: ClassVar[Dict[Platform, Type[PostProcessor]]] = dict(...)  # 가능 타입으로 Class Variable임을 명시
> ```

### `postprocessor_type`

postprocessor_type은 postprocessor 변수 옆에 존재하면 어색하다는 의견에 대해서는 postprocessor_type 값을 없애고 각 모델의 PostProcessor 가 [RustPostProcessor | PythonPostProcessor](https://github.com/furiosa-ai/furiosa-models/pull/166/commits/1339aaceb92ccd258ddc55f0cfa08b775ac651a7#diff-f8568076c24d1283bb9b0c711bd6485d1d7363a9d90e248b4457d18f3f1cc57bR59-R64) 를 상속받아 만들게 했습니다.

나중에 어떤 후처리기인지 `isinstance(SomePostProcessor, PythonPostProcessor)` 등으로 알 수 있습니다. class variable로 platform 변수로도 가지고 있도록 했는데요(postprocessor_type과 같은), 당장 사용되는 곳은 없지만 편의를 위해 넣어 뒀습니다.

2023-08-10 14:03 UTC, furiosa-infra commented
## Pip freeze result for all
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.2.1
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.14.0
dvc-data==2.12.2
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.76
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.2.1
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-10 15:34 UTC, furiosa-infra commented
bcd8f03 fix: raise FileNotFound with proper Path
```

---------------------------------------------------------------------------------------------------------- benchmark: 9 tests ----------------------------------------------------------------------------------------------------------
Name (time in ms)                                                  Min                   Max                Mean              StdDev              Median                 IQR            Outliers       OPS            Rounds  Iterations
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy                                1.4491 (1.0)        845.0273 (16.76)      7.5713 (1.0)        7.1387 (1.76)       5.4727 (1.0)        2.3284 (1.95)    4705;7064  132.0768 (1.0)       50000           1
test_efficientnetb0_accuracy                                    4.8905 (3.37)       269.0154 (5.34)      12.3721 (1.63)       6.5440 (1.62)      11.7471 (2.15)       2.0067 (1.68)    1114;3092   80.8271 (0.61)      50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy       5.3941 (3.72)        50.4155 (1.0)       12.3447 (1.63)       5.7216 (1.41)       9.4602 (1.73)       5.4356 (4.55)      769;379   81.0064 (0.61)       5000           1
test_mlcommons_ssd_mobilenet_accuracy                           6.5957 (4.55)       259.1938 (5.14)      11.3747 (1.50)       4.0491 (1.0)       10.6603 (1.95)       1.1939 (1.0)       469;791   87.9145 (0.67)       5000           1
test_efficientnetv2s_accuracy                                   7.2850 (5.03)       247.3470 (4.91)      14.7676 (1.95)       6.4752 (1.60)      14.1720 (2.59)       2.4803 (2.08)     968;1624   67.7159 (0.51)      50000           1
test_yolov5m_accuracy                                           8.9784 (6.20)       248.2065 (4.92)      16.8011 (2.22)      11.8134 (2.92)      13.0782 (2.39)       5.9664 (5.00)     885;1103   59.5199 (0.45)      10000           1
test_yolov5l_accuracy                                          12.3175 (8.50)       249.6775 (4.95)      17.2379 (2.28)       6.9053 (1.71)      15.9237 (2.91)       3.2749 (2.74)      353;451   58.0116 (0.44)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy       39.1387 (27.01)      931.0094 (18.47)     52.8140 (6.98)      12.9399 (3.20)      51.6798 (9.44)       4.5644 (3.82)        30;88   18.9344 (0.14)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          103.2649 (71.26)    1,486.2679 (29.48)    285.4861 (37.71)    104.5879 (25.83)    286.1903 (52.29)    104.1649 (87.25)     810;223    3.5028 (0.03)       5000           1
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-11 04:39 UTC, senokay approved these changes
제가 지적했던 문제는 모두 해결된 것 같고, 사소한 부분만 더 코멘트 남겼습니다. :-)

2023-08-11 04:39 UTC, senokay commented on furiosa/models/client/api.py
> +            ) and not isinstance(model, (vision.YOLOv5m, vision.YOLOv5l))
이게 루프 안에 들어 있을 필요가 있나요?

2023-08-11 04:39 UTC, senokay commented on constraints.txt
> +opencv-python-headless==4.8.0.76
Lock file 같은 것과는 달리 테스트 전용으로만 쓰므로, 주석으로 CI를 위해 사용된다고 명시해 주면 좋을 것 같습니다. (파일명을 `ci-constraints.txt` 등으로 바꾸는 방법도 있습니다.)

2023-08-11 04:42 UTC, senokay commented on tests/bench/test_efficientnet_b0.py
> +    runner.close()
여기 포함해서 몇 군데에 `runner.close()`를 직접 부르는 코드가 남아 있는데 이것도 context manager로 바꿔도 될 것 같습니다. (제가 파악하기로는 테스트 코드에만 있습니다.)

2023-08-11 04:43 UTC, furiosamg commented on tests/bench/test_efficientnet_b0.py
> +    runner.close()
이게 제가 알기로 pytest-benchmark 제약 사항 때문에 맨 처음에 이렇게 적혔던 것으로 알고 있는데요, context manager 로 바꿀 수 있으면 바꿔보겠습니다.

2023-08-11 17:48 UTC, furiosamg commented on constraints.txt
> +opencv-python-headless==4.8.0.76
8638e44aae171a25c9 에서 둘 다 적용했습니다

2023-08-11 17:49 UTC, furiosamg commented on furiosa/models/client/api.py
> +            ) and not isinstance(model, (vision.YOLOv5m, vision.YOLOv5l))
https://github.com/furiosa-ai/furiosa-models/pull/166/commits/8638e44aae171a25c9407c84b32c9b51af92e760#diff-2225a40b0e1eafbbfbe794b416dff9e2e6ae9bacfb0aba62d015320ab009a82fR113-L130
에서 위치를 옮기고 주석도 자세히 바꿨습니다.

2023-08-11 18:28 UTC, furiosa-infra commented
## Pip freeze result for all
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.2.1
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.3
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.15.0
dvc-data==2.13.1
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.76
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.2.1
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-11 19:36 UTC, furiosa-infra commented
48968de ci: wait for the docker image in regression test
```

-------------------------------------------------------------------------------------------------------- benchmark: 9 tests --------------------------------------------------------------------------------------------------------
Name (time in ms)                                                 Min                 Max                Mean             StdDev              Median                IQR             Outliers       OPS            Rounds  Iterations
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy                               1.2228 (1.0)       62.9638 (2.63)       4.4538 (1.0)       1.6658 (1.39)       4.0948 (1.0)       0.8455 (1.0)      5295;7429  224.5265 (1.0)       50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy      4.4351 (3.63)      27.5367 (1.15)       8.4058 (1.89)      1.2025 (1.0)        8.4014 (2.05)      1.3143 (1.55)      1240;208  118.9650 (0.53)       5000           1
test_efficientnetb0_accuracy                                   4.7122 (3.85)     269.3500 (11.25)     12.7324 (2.86)      6.9041 (5.74)      12.0508 (2.94)      2.4775 (2.93)     1350;2933   78.5399 (0.35)      50000           1
test_mlcommons_ssd_mobilenet_accuracy                          5.3257 (4.36)     201.1761 (8.40)      10.8406 (2.43)      2.9063 (2.42)      10.8880 (2.66)      0.8978 (1.06)       117;562   92.2461 (0.41)       5000           1
test_efficientnetv2s_accuracy                                  6.6130 (5.41)     248.0485 (10.36)     14.2771 (3.21)      6.1561 (5.12)      13.7078 (3.35)      2.9179 (3.45)     1291;1431   70.0424 (0.31)      50000           1
test_yolov5m_accuracy                                          7.8217 (6.40)      23.9403 (1.0)       11.2746 (2.53)      1.5615 (1.30)      11.0394 (2.70)      1.9354 (2.29)      2919;251   88.6947 (0.40)      10000           1
test_yolov5l_accuracy                                         11.0181 (9.01)      60.5568 (2.53)      15.1499 (3.40)      1.8168 (1.51)      14.9050 (3.64)      2.1688 (2.57)      2548;229   66.0069 (0.29)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy      33.3784 (27.30)    527.9876 (22.05)     50.0716 (11.24)    11.6877 (9.72)      49.5007 (12.09)     2.4479 (2.90)        42;258   19.9714 (0.09)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          93.2997 (76.30)    947.3944 (39.57)    125.4364 (28.16)    24.0915 (20.03)    122.2380 (29.85)    17.8974 (21.17)      421;172    7.9722 (0.04)       5000           1
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-12 08:11 UTC, furiosamg commented on tests/bench/test_efficientnet_b0.py
> +    runner.close()
8638e44aae171 에서 해 보니 잘 되네요 감사합니다 모두 반영했습니다.

2023-08-12 08:11 UTC, furiosa-infra commented
## Pip freeze result for all
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.2.1
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.3
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.15.0
dvc-data==2.13.1
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.76
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.2.1
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-12 08:34 UTC, furiosa-infra commented
## Pip freeze result for all
<details><summary>pip freeze result</summary><pre>
aiobotocore==2.5.4
aiofiles==23.2.1
aiohttp==3.8.5
aiohttp-retry==2.8.3
aioitertools==0.11.0
aiosignal==1.3.1
amqp==5.1.1
annotated-types==0.5.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.3
asyncssh==2.13.2
atpublic==4.0
attrs==23.1.0
billiard==4.1.0
boto3==1.28.17
botocore==1.31.17
celery==5.3.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.3.0
cmake==3.27.1
colorama==0.4.6
configobj==5.0.8
contourpy==1.1.0
cryptography==41.0.3
cycler==0.11.0
Cython==3.0.0
dictdiffer==0.9.0
diskcache==5.6.1
distro==1.8.0
dpath==2.1.6
dulwich==0.21.5
dvc==3.15.1
dvc-data==2.13.1
dvc-http==2.30.2
dvc-objects==0.25.0
dvc-render==0.5.3
dvc-s3==2.23.0
dvc-studio-client==0.13.0
dvc-task==0.3.0
exceptiongroup==1.1.2
filelock==3.12.2
flatten-dict==0.4.2
flufl.lock==7.1.1
fonttools==4.42.0
frozenlist==1.4.0
fsspec==2023.6.0
funcy==2.0
furiosa-common==0.10.0
furiosa-models @ file:///app
furiosa-native-postprocess==0.9.0.dev0
furiosa-native-runtime==0.10.0
furiosa-quantizer==0.10.0
furiosa-quantizer-impl==0.10.0
furiosa-runtime==0.10.0
furiosa-tools==0.10.0
gitdb==4.0.10
GitPython==3.1.32
grandalf==0.8
hydra-core==1.3.2
idna==3.4
importlib-resources==6.0.1
iniconfig==2.0.0
iterative-telemetry==0.0.8
Jinja2==3.1.2
jmespath==1.0.1
kiwisolver==1.4.4
kombu==5.3.1
lit==17.0.0rc2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
multidict==6.0.4
multipledispatch==1.0.0
networkx==3.1
numpy==1.25.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
omegaconf==2.3.0
onnx==1.14.0
opencv-python-headless==4.8.0.76
orjson==3.9.4
packaging==23.1
pandas==2.0.3
pathspec==0.11.2
Pillow==10.0.0
platformdirs==3.10.0
pluggy==1.2.0
prompt-toolkit==3.0.39
protobuf==4.24.0
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.1
pycocotools==2.0.6
pycparser==2.21
pydantic==2.1.1
pydantic_core==2.4.0
pydot==1.4.2
pygit2==1.12.2
Pygments==2.16.1
pygtrie==2.5.0
pyparsing==3.0.9
pytest==7.4.0
pytest-asyncio==0.17.2
pytest-benchmark==4.0.0
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
requests==2.31.0
rich==13.5.2
ruamel.yaml==0.17.32
ruamel.yaml.clib==0.2.7
s3fs==2023.6.0
s3transfer==0.6.1
scmrepo==1.2.1
shortuuid==1.0.11
shtab==1.6.4
six==1.16.0
smmap==5.0.0
sqltrie==0.7.0
sympy==1.12
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.1
torch==2.0.1
torchvision==0.15.2
tqdm==4.66.1
triton==2.0.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==1.26.16
vine==5.0.0
voluptuous==0.13.1
wcwidth==0.2.6
wrapt==1.15.0
yarl==1.9.2
zc.lockfile==3.0.post1
zipp==3.16.2
</pre></details>

2023-08-12 09:50 UTC, furiosa-infra commented
b850c47 fix: address reviews from @senokay
```

-------------------------------------------------------------------------------------------------------- benchmark: 9 tests -------------------------------------------------------------------------------------------------------
Name (time in ms)                                                 Min                 Max                Mean             StdDev              Median                IQR            Outliers       OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_mlcommons_resnet50_accuracy                               1.3115 (1.0)       63.9709 (1.96)       5.9993 (1.0)       4.1553 (1.46)       4.4770 (1.0)       1.9330 (2.25)    5633;5614  166.6857 (1.0)       50000           1
test_mlcommons_ssd_mobilenet_with_native_rust_pp_accuracy      4.0134 (3.06)      32.5747 (1.0)        9.9397 (1.66)      3.5616 (1.25)       8.5509 (1.91)      1.8593 (2.16)    1031;1050  100.6070 (0.60)       5000           1
test_efficientnetb0_accuracy                                   4.4337 (3.38)     310.2628 (9.52)      12.7090 (2.12)      7.1238 (2.50)      12.1536 (2.71)      2.2786 (2.65)    1154;3222   78.6842 (0.47)      50000           1
test_mlcommons_ssd_mobilenet_accuracy                          6.0214 (4.59)     222.5211 (6.83)      10.5439 (1.76)      3.1715 (1.11)      10.5615 (2.36)      0.8598 (1.0)        70;532   94.8418 (0.57)       5000           1
test_efficientnetv2s_accuracy                                  6.4203 (4.90)     259.5345 (7.97)      14.3399 (2.39)      6.2625 (2.20)      13.8163 (3.09)      2.2419 (2.61)    1066;2399   69.7357 (0.42)      50000           1
test_yolov5m_accuracy                                          7.9143 (6.03)      99.2324 (3.05)      12.6384 (2.11)      5.5192 (1.94)      11.2254 (2.51)      3.5333 (4.11)      657;544   79.1237 (0.47)      10000           1
test_yolov5l_accuracy                                         11.2186 (8.55)      88.2726 (2.71)      14.9905 (2.50)      2.8465 (1.0)       14.5897 (3.26)      1.7955 (2.09)      589;371   66.7087 (0.40)      10000           1
test_mlcommons_ssd_resnet34_with_native_rust_pp_accuracy      38.3107 (29.21)    553.0120 (16.98)     48.7515 (8.13)      7.4745 (2.63)      48.4227 (10.82)     2.1452 (2.50)       76;214   20.5122 (0.12)       5000           1
test_mlcommons_ssd_resnet34_accuracy                          93.4193 (71.23)    994.5578 (30.53)    184.6635 (30.78)    56.7471 (19.94)    187.9901 (41.99)    68.5190 (79.69)     1714;73    5.4153 (0.03)       5000           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Legend:
  Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range) from 1st Quartile and 3rd Quartile.
  OPS: Operations Per Second, computed as 1 / Mean
```

2023-08-14 07:49 UTC, libc-furiosa reviewed
전체적으로 훑어보았습니다.
이미 많은 개선을 해 주셨는데요, 사소한 부분들에 커멘트를 남겼습니다.
확인 부탁드립니다. 감사합니다.

2023-08-14 07:49 UTC, libc-furiosa commented on tests/bench/test_ssd_mobilenet.py
> +    runner = create_runner(model.model_source())
다른 테스트들과는 달리 `with`로 runner를 생성하지 않고 있는데, 이유가 있는 것일까요?

2023-08-14 07:49 UTC, libc-furiosa commented on tekton/furiosa-models-ci/pr-trigger.yaml
> +                        - npu
affinity는 생략해도 될 것 같습니다. (resources의 npu 지정에 의해 충족됨)

2023-08-14 07:49 UTC, libc-furiosa commented on tekton/furiosa-models-ci/pr-trigger.yaml
> +                        - npu
affinity는 생략해도 될 것 같습니다. (resources의 npu 지정에 의해 충족됨)

2023-08-14 07:49 UTC, libc-furiosa commented on furiosa/models/vision/yolov5/core.py
>              images: Color images have (NCHW: Batch, Channel, Height, Width) dimensions.
이 PR과는 관계가 없습니다만, input image는 NHWC가 아닌지 궁금합니다.
아래의 `transpose([2, 0, 1])` 이 NHWC -> NCHW 를 하는게 아닌가 해서요.

2023-08-14 07:49 UTC, libc-furiosa commented on docs/examples/ssd_mobilenet_onnx.py
> +    inputs, contexts = mobilenet.preprocess(image, skip_quantize=False)
이 커멘트는 가볍게 드리는 의견입니다. 다른 분들도 견해를 들려주시면 좋을 것 같습니다.

기존의 `with_quantize`나 이번의 `skip_quantize` 라는 이름을 보았을 때,
quantize를 왜 해야하는지? 언제 skip 하는지? 어떤 효과를 주는지? 마음대로 설정할 수 있는지? 에 대한 의문이 생깁니다.
context를 아는 경우에는 조금만 생각해보면 알 수 있지만, 아닌 일반 사용자는 쉽게 이해할 수 있을지 모르겠네요.

저는 모델의 입력 텐서 타입이 float인지 int(uint)인지가 중요하지 않을까, 하고 생각이 들었는데요,
float 라면 image를 read한 값을 형변환을 할 것이고, uint라면 변환을 생략할 것이기 때문입니다.
결과적으로 quantize 여부는 타입에 의존적이게 되므로, 이를 인자로 True/False로 지정하여 선택이 가능한 것 처럼 보이기보다는
모델이 어떤 타입인지를 표현하는 인자가 되면 보다 설명이 간단해지지 않을까 싶습니다.

2023-08-14 09:23 UTC, furiosamg commented on docs/examples/ssd_mobilenet_native.py
> +mobilenet = SSDMobileNet(postprocessor_type="Rust")
Platform 이 strEnum 이기도 하고, 사용자가 편하게 문자열로 선택하면 좋을 것 같아서 그렇게 했습니다. 사실 strict 하게 typing 하자면 Platform만 주는 것이 맞긴 한데요, 모델 주는 사용자 편의성이 중요한 프로젝트라 임의로 그렇게 했습니다. 아님 혹시 더 좋은 방법이 있을까요?

2023-08-14 10:49 UTC, furiosamg commented on docs/examples/ssd_mobilenet.py
> +with create_runner(mobilenet.model_source()) as create_runner:
dc0aecc 에서 반영했습니다.

2023-08-14 10:50 UTC, furiosamg commented on furiosa/models/data/enf_generator.py
> +    dfg = quantize(onnx_model, calib_ranges)
감사합니다! dc0aecc 에서 반영했습니다.

2023-08-14 10:51 UTC, furiosamg commented on tests/bench/test_ssd_mobilenet.py
> +    runner = create_runner(model.model_source())
dc0aecc에서 반영했습니다.

2023-08-14 10:51 UTC, furiosamg commented on tekton/furiosa-models-ci/pr-trigger.yaml
> +                        - npu
dc0aecc에서 반영했습니다.

2023-08-14 10:51 UTC, furiosamg commented on tekton/furiosa-models-ci/pr-trigger.yaml
> +                        - npu
dc0aecc 에서 반영했습니다.

2023-08-16 10:03 UTC, furiosamg commented on docs/examples/ssd_mobilenet_onnx.py
> +    inputs, contexts = mobilenet.preprocess(image, skip_quantize=False)
cad487e 에서 with_scaling이라는 파라미터로 바꾸었고 설명을 추가했습니다. 구두로 논의 나눈 내용이라 자세히 적지는 않겠습니다. 감사합니다

2023-08-18 21:29 UTC, hyunsik commented on docs/examples/ssd_mobilenet_onnx.py
> +    inputs, contexts = mobilenet.preprocess(image, skip_quantize=False)
> 모델이 어떤 타입인지를 표현하는 인자가 되면 보다 설명이 간단해지지 않을까 싶습니다.

이 PR 이 크기 때문에 이 관련해서는 별도 PR 로 다루면 좋을 것 같기는 합니다만, 조금 설명을 듣고 싶은데요. with_scaling 이라는 이름이 여전히 모호한 느낌이 있는데요. 제가 인용한 병찬님이 말씀 처럼 `use_fp32 = True` 같은 옵션이나 dtype을 직접 넣는 것을 고려하지 않았는지 궁금하기도 합니다.

2023-08-18 21:29 UTC, hyunsik approved these changes
고생 많으셨습니다. `with_scaling` 옵션에 대한 의견 코멘트로 달았습니다. 이 관련 논의와 변경은 필요한 경우에 별도 이슈나 PR 에서 해도 좋을 것 같습니다. 바로 머지하셔도 좋을 것 같습니다.

2023-08-18 21:30 UTC, merged